/**
 * ===========================================================================================
 * THE CROSS-CLIENT KDF VECTOR TABLE. `docs/decisions/0015` §D and its NFC amendment.
 * ===========================================================================================
 *
 * ONE CONTRACT SET, THREE IMPLEMENTATIONS: the web client (`platform/web/src/api/kdf.ts`), the
 * Apple client (Swift, not yet written), and the enrolment tool
 * (`platform/core/identity/tools/seed-principal.ts`), which derives the client value on the
 * operator's behalf and is therefore a client of this rule whatever directory it lives in.
 *
 * All three must produce BYTE-IDENTICAL output. `0015` states the consequence of divergence in
 * the plainest available terms: *"The user enrols on one platform and cannot log in on the
 * other, and the failure presents as a wrong password, which is the least diagnosable form it
 * could take."* Nothing stores a plaintext password, so a divergence discovered after enrolment
 * cannot be migrated — the account is simply gone.
 *
 * ===========================================================================================
 * EVERY NON-ASCII CHARACTER IN THIS FILE IS A `\uXXXX` ESCAPE. THIS IS NOT A STYLE CHOICE.
 * ===========================================================================================
 *
 * The whole point of the composed/decomposed pair is that the two are DIFFERENT BYTES that look
 * identical. A literal written into this file can be normalised by an editor, a copy-paste, a
 * clipboard, a git filter, or the tool that wrote it — and a decomposed vector that silently
 * became composed on disk still passes, while testing nothing at all. Escapes cannot be
 * normalised, so the vector on disk is the vector that was intended.
 *
 * `assertNormalisationFormsAreDistinct` below re-checks this at run time anyway, because a rule
 * that depends on a future editor's discipline is not a rule.
 *
 * ===========================================================================================
 * THE NORMATIVE RULE, RESTATED HERE BECAUSE THE VECTORS ARE ONLY MEANINGFUL BESIDE IT
 * ===========================================================================================
 *
 *   identifier  validate ASCII 0x21-0x7E, length 3-254, contains '@'  (whitespace REFUSED,
 *               never trimmed), then NFKC, then ASCII-ONLY case folding A-Z -> a-z
 *               (NOT `toLowerCase()`)
 *   password    NFC only. No case folding, no trimming, no ASCII restriction.
 *               RFC 8265 PRECIS `OpaqueString`.
 *   derivation  PBKDF2-SHA256(password_utf8, salt = normalised_identifier_utf8, 600000, 32)
 *   encoding    base64url, unpadded, exactly 43 characters
 *
 * ===========================================================================================
 * WHAT THE EXPECTED COLUMN IS, AND WHY IT IS NOT COMPUTED BY EITHER CLIENT
 * ===========================================================================================
 *
 * Every expected value is produced by `node:crypto`'s `pbkdf2Sync` — a different implementation
 * from the `crypto.subtle` both TypeScript clients use. A table generated by the web client and
 * then checked against the web client would agree with itself. `app-agent` should check Swift's
 * output against THIS reference, not against the web client's, for the same reason.
 */

import { pbkdf2Sync } from 'node:crypto';
import { Suite, assertEqual, assertTrue } from '../../harness/runner.ts';
import {
  isSubmittableIdentifier,
  normalizeIdentifier,
  toBase64Url,
} from '../../../../platform/core/identity/credential-store.ts';
import {
  deriveCredential,
  deriveLoginCredential,
  normalizePassword,
  isSubmittableIdentifier as webIsSubmittableIdentifier,
  normalizeIdentifier as webNormalizeIdentifier,
} from '../../../../platform/web/src/api/kdf.ts';
import { deriveClientValue } from '../../../../platform/core/identity/tools/seed-principal.ts';

const ITERATIONS = 600_000;
const OUTPUT_BYTES = 32;

// The characters the interesting vectors are built from. Escapes only; see the header.
/** U+00E9 LATIN SMALL LETTER E WITH ACUTE. One code point. */
const E_ACUTE_COMPOSED = 'é';
/** 'e' + U+0301 COMBINING ACUTE ACCENT. Two code points; NFC folds it to the above. */
const E_ACUTE_DECOMPOSED = 'é';
/** U+FB01 LATIN SMALL LIGATURE FI. NFC leaves it; NFKC would expand it to 'fi'. */
const LIGATURE_FI = 'ﬁ';
/** U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE. The `toLowerCase()` divergence. */
const DOTTED_CAPITAL_I = 'İ';
/** U+00E4 LATIN SMALL LETTER A WITH DIAERESIS. */
const A_DIAERESIS = 'ä';
/** U+00F6 LATIN SMALL LETTER O WITH DIAERESIS. */
const O_DIAERESIS = 'ö';
/** U+0308 COMBINING DIAERESIS, for building the decomposed forms of the two above. */
const COMBINING_DIAERESIS = '̈';
/** U+1F511 KEY. A surrogate pair in UTF-16; four bytes in UTF-8, six in CESU-8. */
const ASTRAL_KEY = '\u{1f511}';

/**
 * ===========================================================================================
 * ANNOTATED `: string`, AND IT IS NOT A CAST AND NOT A SILENCING. READ THIS BEFORE REMOVING IT.
 * ===========================================================================================
 *
 * Without the annotation TypeScript infers two distinct STRING LITERAL types for these, sees that
 * `PASSWORD_COMPOSED !== PASSWORD_DECOMPOSED` can never be false, and reports TS2367 — *"this
 * comparison appears to be unintentional... no overlap"*. `npm run typecheck:tests` was red on it.
 *
 * **THE TEMPTING FIX IS A CAST, AND THE CAST WOULD BE THE WRONG INSTINCT.** The previous
 * `qa-agent` flagged that and was right: a cast asserts something about a value in order to stop
 * the compiler talking, and the next reader cannot tell a silencing from a fact.
 *
 * *** BUT THE COMPILE-TIME SIGNAL IS INVERTED, AND THAT IS WHY THE ANNOTATION IS CORRECT. ***
 * The runtime assertion below exists to catch ONE failure: an editor, a tool or a merge
 * normalising this file on disk, which would make the two vectors identical and every NFC vector
 * in the table vacuous. Consider what TypeScript does in each state:
 *
 *   VECTORS STILL DISTINCT (correct)  -> two different literal types -> TS2367 IS REPORTED.
 *   VECTORS NORMALISED ON DISK (bug)  -> one identical literal type  -> TS2367 DISAPPEARS.
 *
 * **The diagnostic fires when the file is right and goes silent when it is wrong.** It is not a
 * check that was designed; it is a tautology detector pointed at a deliberate tautology, and
 * keeping the gate red for it would mean keeping a red gate for a signal that means the opposite
 * of what a reader would assume.
 *
 * `: string` IS A TRUE STATEMENT ABOUT BOTH VALUES and changes nothing at runtime. The assertion
 * in `the composed and decomposed vectors really are different byte sequences` still runs, still
 * compares the real strings, and still goes red the day the file is normalised — which is the
 * check that was actually built for this, and the only one that behaves the right way round.
 */
const PASSWORD_COMPOSED: string = `caf${E_ACUTE_COMPOSED}-passphrase-0002`;
const PASSWORD_DECOMPOSED: string = `caf${E_ACUTE_DECOMPOSED}-passphrase-0002`;
const PASSWORD_LIGATURE = `a${LIGATURE_FI}ne-passphrase-0003`;
const PASSWORD_LIGATURE_EXPANDED = 'afine-passphrase-0003';

// =============================================================================================
// THE SHARED SET — the vectors that bind the clients TO EACH OTHER, not each to itself.
// =============================================================================================
//
// Each client verifying composed==decomposed *in its own language* proves only that the client
// is self-consistent. What binds them is an agreed EXPECTED OUTPUT, and these three carry one.
//
// SV1 and SV2 arrived confirmed across four implementations — web's shipped `kdf.ts`, Apple's
// hand-written PBKDF2, Apple's `CCKeyDerivationPBKDF`, and a Python `hashlib.pbkdf2_hmac`. This
// file adds a fifth, `node:crypto`, and asserts the values rather than restating them.
//
// SV3 EXISTS BECAUSE SV2 IS BLIND TO THE DEFECT IT LOOKS LIKE IT COVERS, which is the most
// valuable thing anyone found in this slice. `ä` and `ö` have NO compatibility decomposition, so
// NFKC and NFC are the same function over `pässwörd` — SV2 passes with the two calls
// deliberately exchanged. Only a character that HAS a compatibility decomposition can tell them
// apart. Two defect classes, two vectors, neither substituting for the other:
//
//   a client skips normalisation entirely   -> SV2 (composed vs decomposed must MATCH)
//   a client uses NFKC where NFC belongs    -> SV3 (ligature vs plain must DIFFER)
//
const SHARED_EMAIL_RAW = 'Test@Example.COM';
const SHARED_EMAIL_NORMALIZED = 'test@example.com';
/** UTF-8 of the normalised email, which is the PBKDF2 salt. Pinned so a fault localises. */
const SHARED_SALT_UTF8_HEX = '74657374406578616d706c652e636f6d';

/** SV1 — ASCII. Confirmed: web, Apple ×2, Python, and `node:crypto` here. */
const SV1_PASSWORD = 'correct horse battery staple';
const SV1_EXPECTED = 'vDKY7nW_Ay6C6JtXqe0QC9cBRmBfrTgqxOmnxr72Kqw';

/** SV2 — non-ASCII, both encodings, one expected output. Catches a skipped NFC. */
const SV2_COMPOSED = `p${A_DIAERESIS}ssw${O_DIAERESIS}rd`;
const SV2_DECOMPOSED = `pa${COMBINING_DIAERESIS}sswo${COMBINING_DIAERESIS}rd`;
const SV2_EXPECTED = 'ikIunD3491AfgeVOMPonp2D_bYFaLhDBzi1kIWMX004';
const SV2_COMPOSED_UTF8_HEX = '70c3a4737377c3b67264';
const SV2_DECOMPOSED_UTF8_HEX = '7061cc887373776fcc887264';

/** SV3 — the swap catcher. These two MUST derive DIFFERENT keys. */
const SV3_LIGATURE = `${LIGATURE_FI}nance`;
const SV3_PLAIN = 'finance';

/** The reference implementation. Independent of both clients by construction. */
export function referenceDerive(password: string, normalizedIdentifier: string): string {
  return toBase64Url(
    new Uint8Array(
      pbkdf2Sync(
        Buffer.from(password.normalize('NFC'), 'utf8'),
        Buffer.from(normalizedIdentifier, 'utf8'),
        ITERATIONS,
        OUTPUT_BYTES,
        'sha256',
      ),
    ),
  );
}

export type KdfVector = {
  readonly id: string;
  /** What the user types into the email field, before any normalisation. */
  readonly rawIdentifier: string;
  /** What the user types into the password field, before any normalisation. */
  readonly password: string;
  /** What the normalisation rule must produce from `rawIdentifier`. */
  readonly expectedNormalizedIdentifier: string;
  readonly note: string;
};

/**
 * THE TABLE. `app-agent` implements Swift against this file.
 *
 * Every password here is synthetic and none is used anywhere else. The identifiers use
 * `.invalid`, which is reserved by RFC 2606 and cannot resolve.
 */
export const KDF_VECTORS: readonly KdfVector[] = [
  {
    id: 'ascii-baseline',
    rawIdentifier: 'operator@example.invalid',
    password: 'baseline-password-0001',
    expectedNormalizedIdentifier: 'operator@example.invalid',
    note: 'The control. Pure ASCII on both sides; nothing to normalise.',
  },
  {
    id: 'identifier-mixed-case',
    rawIdentifier: 'Operator.ONE@Example.INVALID',
    password: 'baseline-password-0001',
    expectedNormalizedIdentifier: 'operator.one@example.invalid',
    note: 'ASCII case folding on the identifier only. The password is NOT case folded.',
  },
  {
    id: 'password-case-is-significant',
    rawIdentifier: 'operator@example.invalid',
    password: 'BASELINE-PASSWORD-0001',
    expectedNormalizedIdentifier: 'operator@example.invalid',
    note: 'Same letters as ascii-baseline in upper case. MUST derive a DIFFERENT key.',
  },
  {
    id: 'password-decomposed',
    rawIdentifier: 'operator@example.invalid',
    password: PASSWORD_DECOMPOSED,
    expectedNormalizedIdentifier: 'operator@example.invalid',
    note: 'THE AMENDMENT VECTOR. MUST derive the same key as password-composed.',
  },
  {
    id: 'password-composed',
    rawIdentifier: 'operator@example.invalid',
    password: PASSWORD_COMPOSED,
    expectedNormalizedIdentifier: 'operator@example.invalid',
    note: 'THE AMENDMENT VECTOR. MUST derive the same key as password-decomposed.',
  },
  {
    id: 'password-nfkc-would-destroy-entropy',
    rawIdentifier: 'operator@example.invalid',
    password: PASSWORD_LIGATURE,
    expectedNormalizedIdentifier: 'operator@example.invalid',
    note: 'MUST NOT equal the same passphrase written "afine". NFKC here would be a defect.',
  },
  {
    id: 'password-with-surrounding-space',
    rawIdentifier: 'operator@example.invalid',
    password: '  spaced-passphrase-0004  ',
    expectedNormalizedIdentifier: 'operator@example.invalid',
    note: 'The password is NOT trimmed. MUST differ from the trimmed form.',
  },
  {
    id: 'password-astral-emoji',
    rawIdentifier: 'operator@example.invalid',
    password: `astral-${ASTRAL_KEY}-passphrase-0005`,
    expectedNormalizedIdentifier: 'operator@example.invalid',
    note: 'Catches a client that encodes surrogate pairs separately (CESU-8) rather than UTF-8.',
  },
  {
    id: 'identifier-plus-tag',
    rawIdentifier: 'Operator+Beta@Example.Invalid',
    password: 'baseline-password-0001',
    expectedNormalizedIdentifier: 'operator+beta@example.invalid',
    note: 'A "+" tag is preserved, not stripped. Two tags are two different accounts.',
  },
];

/**
 * THE SHARED SET, EXPORTED FOR `app-agent`. Each row carries an AGREED EXPECTED OUTPUT.
 *
 * This is the table that binds the clients to each other. `KDF_VECTORS` above is broader but
 * most of its rows assert agreement with the local reference; these three assert agreement with
 * a value four other implementations have already produced.
 */
export const SHARED_VECTORS: readonly {
  readonly id: string;
  readonly rawIdentifier: string;
  readonly normalizedIdentifier: string;
  readonly password: string;
  readonly expected: string;
  readonly note: string;
}[] = [
  {
    id: 'SV1-ascii',
    rawIdentifier: SHARED_EMAIL_RAW,
    normalizedIdentifier: SHARED_EMAIL_NORMALIZED,
    password: SV1_PASSWORD,
    expected: SV1_EXPECTED,
    note: 'Baseline. Confirmed across web, Apple x2, Python and node:crypto.',
  },
  {
    id: 'SV2-composed',
    rawIdentifier: SHARED_EMAIL_RAW,
    normalizedIdentifier: SHARED_EMAIL_NORMALIZED,
    password: SV2_COMPOSED,
    expected: SV2_EXPECTED,
    note: 'Catches a client that skipped normalisation. BLIND to the NFC/NFKC swap.',
  },
  {
    id: 'SV2-decomposed',
    rawIdentifier: SHARED_EMAIL_RAW,
    normalizedIdentifier: SHARED_EMAIL_NORMALIZED,
    password: SV2_DECOMPOSED,
    expected: SV2_EXPECTED,
    note: 'Same expected output as SV2-composed. That equality IS the test.',
  },
  {
    id: 'SV3-ligature',
    rawIdentifier: SHARED_EMAIL_RAW,
    normalizedIdentifier: SHARED_EMAIL_NORMALIZED,
    password: SV3_LIGATURE,
    expected: '',
    note:
      'MUST NOT equal SV3-plain. The expected value is left empty deliberately: the property is ' +
      'INEQUALITY with SV3-plain, and publishing a value invites a client to hard-code it.',
  },
  {
    id: 'SV3-plain',
    rawIdentifier: SHARED_EMAIL_RAW,
    normalizedIdentifier: SHARED_EMAIL_NORMALIZED,
    password: SV3_PLAIN,
    expected: '',
    note: 'MUST NOT equal SV3-ligature. Catches NFKC used where NFC belongs.',
  },
];

/** Identifiers that MUST be refused before any normalisation happens. */
export const REFUSED_IDENTIFIERS: readonly {
  readonly id: string;
  readonly value: string;
  readonly why: string;
}[] = [
  {
    id: 'identifier-turkish-dotted-i',
    value: `${DOTTED_CAPITAL_I}stanbul@example.invalid`,
    why:
      'U+0130 is above U+007E, so the ASCII gate refuses it BEFORE folding. This is the vector ' +
      'where toLowerCase() diverges between JavaScript and Swift; the rule sidesteps the ' +
      'divergence by refusing the input rather than arbitrating the fold.',
  },
  {
    id: 'identifier-leading-space',
    value: ' operator@example.invalid',
    why:
      'Whitespace is REFUSED, never trimmed. JavaScript trim() and Swift ' +
      'trimmingCharacters(in: .whitespacesAndNewlines) trim different character sets.',
  },
  {
    id: 'identifier-trailing-newline',
    value: 'operator@example.invalid\n',
    why: 'A newline is 0x0A, below 0x21.',
  },
  { id: 'identifier-no-at', value: 'operator.example.invalid', why: 'No "@".' },
  { id: 'identifier-too-short', value: '@a', why: 'Below the 3-character minimum.' },
  {
    id: 'identifier-non-ascii-domain',
    value: `operator@ex${A_DIAERESIS}mple.invalid`,
    why: 'RFC 6531 internationalised addresses are out of scope until a decision record says so.',
  },
  {
    id: 'identifier-ligature-fi',
    value: `o${LIGATURE_FI}ce@example.invalid`,
    why:
      'U+FB01 is above U+007E, so it is refused before NFKC could expand it. NFKC stays in the ' +
      'definition for the day the ASCII gate is relaxed by a recorded decision.',
  },
];

export function buildKdfVectorSuite(): Suite {
  const suite = new Suite('AZ2 — cross-client KDF vectors (0015 §D + NFC amendment)');

  // ---------------------------------------------------------------------------------------
  // The meta-check. If this fails, every vector below is testing something other than what it
  // says, and the whole table must be treated as not run.
  // ---------------------------------------------------------------------------------------

  suite.test('the composed and decomposed vectors really are different byte sequences', () => {
    assertTrue(
      'the two encodings on disk are distinct',
      PASSWORD_COMPOSED !== PASSWORD_DECOMPOSED,
      'the decomposed vector has been normalised on disk — the NFC vectors below are vacuous ' +
        'and this table proves nothing about the amendment',
    );
    assertEqual('they converge under NFC', PASSWORD_DECOMPOSED.normalize('NFC'), PASSWORD_COMPOSED);
    assertEqual('the composed form is 20 code units', PASSWORD_COMPOSED.length, 20);
    assertEqual('the decomposed form is 21 code units', PASSWORD_DECOMPOSED.length, 21);
    assertTrue(
      'the ligature vector really contains U+FB01',
      PASSWORD_LIGATURE.includes(LIGATURE_FI),
      'the ligature was expanded on disk',
    );
    assertEqual(
      'NFC does NOT expand the ligature (only NFKC would)',
      PASSWORD_LIGATURE.normalize('NFC'),
      PASSWORD_LIGATURE,
    );
  });

  // ---------------------------------------------------------------------------------------
  // Identifier normalisation. Cheap, so every implementation is checked on every vector.
  // ---------------------------------------------------------------------------------------

  suite.test('identifier normalisation agrees across Core and the web client', () => {
    for (const vector of KDF_VECTORS) {
      assertEqual(
        `${vector.id}: Core normalises to the expected value`,
        normalizeIdentifier(vector.rawIdentifier),
        vector.expectedNormalizedIdentifier,
      );
      assertEqual(
        `${vector.id}: the web client agrees with Core`,
        webNormalizeIdentifier(vector.rawIdentifier),
        normalizeIdentifier(vector.rawIdentifier),
      );
    }
  });

  suite.test('ASCII-only case folding is used, not toLowerCase()', () => {
    const subject = `${DOTTED_CAPITAL_I}@example.invalid`;
    assertEqual('Core leaves U+0130 alone', normalizeIdentifier(subject), subject);
    assertTrue(
      'toLowerCase() would NOT leave it alone, so the two rules really do differ here',
      subject.toLowerCase() !== subject,
      'U+0130 is unchanged by toLowerCase() in this runtime, so this vector no longer ' +
        'discriminates between the two rules and a stronger one is needed',
    );
    assertEqual(
      'the web client leaves it alone too',
      webNormalizeIdentifier(subject),
      subject,
    );
  });

  suite.test('refused identifiers are refused by Core and by the web client alike', () => {
    for (const entry of REFUSED_IDENTIFIERS) {
      assertEqual(
        `${entry.id}: Core refuses (${entry.why})`,
        isSubmittableIdentifier(entry.value),
        false,
      );
      assertEqual(
        `${entry.id}: the web client refuses`,
        webIsSubmittableIdentifier(entry.value),
        false,
      );
    }
  });

  suite.test('a padded identifier is refused rather than trimmed into a valid one', () => {
    const padded = ' operator@example.invalid ';
    assertEqual('the padded identifier is refused', isSubmittableIdentifier(padded), false);
    assertEqual(
      'the trimmed form would have been accepted — so refusing is a real choice, not a no-op',
      isSubmittableIdentifier(padded.trim()),
      true,
    );
  });

  suite.test('the password is NFC-normalised and nothing else', () => {
    assertEqual(
      'composed and decomposed collapse to one value',
      normalizePassword(PASSWORD_DECOMPOSED),
      normalizePassword(PASSWORD_COMPOSED),
    );
    assertEqual(
      'the ligature survives — NFKC is NOT applied',
      normalizePassword(PASSWORD_LIGATURE),
      PASSWORD_LIGATURE,
    );
    assertTrue(
      'the ligature does not collapse to "afine"',
      normalizePassword(PASSWORD_LIGATURE) !== PASSWORD_LIGATURE_EXPANDED,
      'the password was NFKC-normalised, which destroys entropy the user believes they have',
    );
    assertEqual('the password is not case folded', normalizePassword('AbC'), 'AbC');
    assertEqual('the password is not trimmed', normalizePassword('  x  '), '  x  ');
  });

  // ---------------------------------------------------------------------------------------
  // The derivations. 600,000 iterations each, so the vector set is deliberately small.
  // ---------------------------------------------------------------------------------------

  suite.test('the web client matches the independent reference on every vector', async () => {
    for (const vector of KDF_VECTORS) {
      const expected = referenceDerive(vector.password, vector.expectedNormalizedIdentifier);
      assertEqual(`${vector.id}: reference output is 43 characters`, expected.length, 43);
      const actual = await deriveCredential(vector.password, vector.expectedNormalizedIdentifier);
      assertEqual(
        `${vector.id}: web client matches the reference (${vector.note})`,
        actual,
        expected,
      );
    }
  });

  // ---------------------------------------------------------------------------------------
  // THE SHARED SET. These are the vectors that bind web and Apple to each other.
  // ---------------------------------------------------------------------------------------

  suite.test('SV1 (ASCII) — the shipped web client produces the agreed expected output', async () => {
    assertEqual(
      'the shared email normalises to the agreed salt',
      normalizeIdentifier(SHARED_EMAIL_RAW),
      SHARED_EMAIL_NORMALIZED,
    );
    assertEqual(
      'and the salt is the agreed UTF-8 byte sequence',
      Buffer.from(SHARED_EMAIL_NORMALIZED, 'utf8').toString('hex'),
      SHARED_SALT_UTF8_HEX,
    );
    assertEqual(
      'node:crypto — a fifth independent implementation — reproduces the agreed output',
      referenceDerive(SV1_PASSWORD, SHARED_EMAIL_NORMALIZED),
      SV1_EXPECTED,
    );
    assertEqual(
      "the web client's SHIPPED module agrees with all four others",
      await deriveCredential(SV1_PASSWORD, SHARED_EMAIL_NORMALIZED),
      SV1_EXPECTED,
    );
  });

  suite.test('SV2 (non-ASCII) — both encodings reach one agreed output, byte sequences pinned', async () => {
    // The byte sequences are asserted because they localise a failure instantly: wrong BEFORE
    // NFC is an encoding fault, wrong AFTER it is the normalisation call itself.
    assertEqual(
      'the composed form has the agreed UTF-8 bytes',
      Buffer.from(SV2_COMPOSED, 'utf8').toString('hex'),
      SV2_COMPOSED_UTF8_HEX,
    );
    assertEqual(
      'the decomposed form has the agreed UTF-8 bytes',
      Buffer.from(SV2_DECOMPOSED, 'utf8').toString('hex'),
      SV2_DECOMPOSED_UTF8_HEX,
    );
    assertEqual(
      'and NFC maps the decomposed bytes onto the composed ones',
      Buffer.from(SV2_DECOMPOSED.normalize('NFC'), 'utf8').toString('hex'),
      SV2_COMPOSED_UTF8_HEX,
    );

    assertEqual(
      'the shipped web client derives the agreed output from the COMPOSED form',
      await deriveCredential(SV2_COMPOSED, SHARED_EMAIL_NORMALIZED),
      SV2_EXPECTED,
    );
    assertEqual(
      'and the same agreed output from the DECOMPOSED form',
      await deriveCredential(SV2_DECOMPOSED, SHARED_EMAIL_NORMALIZED),
      SV2_EXPECTED,
    );
    assertEqual(
      'node:crypto reproduces it independently',
      referenceDerive(SV2_COMPOSED, SHARED_EMAIL_NORMALIZED),
      SV2_EXPECTED,
    );
  });

  suite.test('SV2 IS BLIND TO THE NFC/NFKC SWAP — recorded, so nobody trusts it for that', () => {
    // Asserted rather than described. If a future Unicode revision ever gave these characters a
    // compatibility decomposition, this case goes red and SV3 stops being load-bearing — which
    // is a thing someone should be told about rather than left to assume either way.
    assertEqual(
      'NFKC and NFC are the SAME function over the composed form',
      SV2_COMPOSED.normalize('NFKC'),
      SV2_COMPOSED.normalize('NFC'),
    );
    assertEqual(
      'and over the decomposed form',
      SV2_DECOMPOSED.normalize('NFKC'),
      SV2_DECOMPOSED.normalize('NFC'),
    );
    assertTrue(
      'so SV2 cannot distinguish the two calls, and SV3 is required',
      SV2_COMPOSED.normalize('NFKC') === SV2_COMPOSED.normalize('NFC'),
      'SV2 has become swap-sensitive; re-derive whether SV3 is still needed',
    );
  });

  suite.test('SV3 (the swap catcher) — the ligature and the plain spelling derive DIFFERENT keys', async () => {
    assertEqual(
      'NFC preserves the ligature',
      SV3_LIGATURE.normalize('NFC'),
      SV3_LIGATURE,
    );
    assertEqual(
      'NFKC would collapse it — which is exactly the defect',
      SV3_LIGATURE.normalize('NFKC'),
      SV3_PLAIN,
    );

    const ligature = await deriveCredential(SV3_LIGATURE, SHARED_EMAIL_NORMALIZED);
    const plain = await deriveCredential(SV3_PLAIN, SHARED_EMAIL_NORMALIZED);
    assertTrue(
      'the shipped web client keeps them distinct — a client using NFKC on the password would ' +
        'collapse these two into one key and pass every other vector in the shared set',
      ligature !== plain,
      `both derived ${ligature}`,
    );
    assertEqual(
      'node:crypto agrees on the ligature output, so Apple has a value to check against',
      ligature,
      referenceDerive(SV3_LIGATURE, SHARED_EMAIL_NORMALIZED),
    );
    assertEqual(
      'and on the plain output',
      plain,
      referenceDerive(SV3_PLAIN, SHARED_EMAIL_NORMALIZED),
    );
  });

  suite.test('SV3 also catches the swap on the IDENTIFIER, in the opposite direction', () => {
    // The two normalisations now sit in the same file applied to different inputs, which is how
    // they get exchanged. The identifier rule is NFKC, so the swap here is the mirror image:
    // using NFC on the identifier would leave a ligature standing where it should collapse.
    //
    // Under the CURRENT rule the ligature identifier is refused by the ASCII gate before NFKC
    // could act, so this asserts the property at the normaliser, where it is observable.
    // `o` + U+FB01 + `ce`. NFKC expands U+FB01 to the two ASCII letters `fi`, giving `ofice` —
    // one `f`, not two. Spelled out because getting it wrong is easy and the wrong expectation
    // is what this case caught on its first run.
    const ligatureIdentifier = `o${LIGATURE_FI}ce@example.invalid`;
    assertEqual(
      'the identifier rule is NFKC and therefore collapses the ligature',
      ligatureIdentifier.normalize('NFKC'),
      'ofice@example.invalid',
    );
    assertTrue(
      'while NFC would not — the two calls are distinguishable on this input',
      ligatureIdentifier.normalize('NFC') !== ligatureIdentifier.normalize('NFKC'),
      'this input no longer distinguishes NFC from NFKC and a new one is needed',
    );
    assertEqual(
      'and the ASCII gate refuses it first, so the collapse is unreachable today',
      isSubmittableIdentifier(ligatureIdentifier),
      false,
    );
  });

  suite.test('deriveLoginCredential returns the normalised email alongside the key', async () => {
    const vector = KDF_VECTORS[1];
    const outcome = await deriveLoginCredential(vector.rawIdentifier, vector.password);
    assertEqual(
      'the email returned is the normalised one',
      outcome.email,
      vector.expectedNormalizedIdentifier,
    );
    assertEqual('the derived key is 43 characters', outcome.derived_key.length, 43);
    assertEqual(
      'the derived key matches the reference',
      outcome.derived_key,
      referenceDerive(vector.password, vector.expectedNormalizedIdentifier),
    );
  });

  suite.test('composed and decomposed passwords derive the SAME key (the NFC amendment)', async () => {
    const decomposed = await deriveCredential(PASSWORD_DECOMPOSED, 'operator@example.invalid');
    const composed = await deriveCredential(PASSWORD_COMPOSED, 'operator@example.invalid');
    assertEqual('the two encodings of one password agree', decomposed, composed);
  });

  suite.test('distinct passwords derive DIFFERENT keys (the table discriminates)', async () => {
    // Without this, the agreement assertions above could be satisfied by an implementation that
    // ignored the password entirely.
    const baseline = await deriveCredential('baseline-password-0001', 'operator@example.invalid');
    const upper = await deriveCredential('BASELINE-PASSWORD-0001', 'operator@example.invalid');
    const spaced = await deriveCredential('  baseline-password-0001  ', 'operator@example.invalid');
    const ligature = await deriveCredential(PASSWORD_LIGATURE, 'operator@example.invalid');
    const expanded = await deriveCredential(
      PASSWORD_LIGATURE_EXPANDED,
      'operator@example.invalid',
    );
    assertTrue('case matters', baseline !== upper, 'the password appears to be case folded');
    assertTrue(
      'surrounding space matters',
      baseline !== spaced,
      'the password appears to be trimmed',
    );
    assertTrue(
      'the ligature is not expanded',
      ligature !== expanded,
      'the password appears to be NFKC-normalised',
    );
  });

  suite.test('the salt is the identifier: one password on two accounts derives differently', async () => {
    const one = await deriveCredential('baseline-password-0001', 'operator@example.invalid');
    const two = await deriveCredential('baseline-password-0001', 'operator2@example.invalid');
    assertTrue(
      'two accounts, two keys',
      one !== two,
      'the identifier is not being used as the PBKDF2 salt',
    );
  });

  // ---------------------------------------------------------------------------------------
  // THE THIRD IMPLEMENTATION. `tools/seed-principal.ts` derives the client value on the
  // operator's behalf, so it is bound by the same rule. If it disagrees with the web client,
  // the enrolled account cannot log in — silently, permanently, presenting as a wrong password,
  // and with no migration available because no plaintext password is stored anywhere.
  // ---------------------------------------------------------------------------------------

  suite.test('the enrolment tool agrees with the web client on an ASCII password', async () => {
    const normalized = 'operator@example.invalid';
    const fromTool = toBase64Url(await deriveClientValue('baseline-password-0001', normalized));
    const fromWeb = await deriveCredential('baseline-password-0001', normalized);
    assertEqual('tool and web agree', fromTool, fromWeb);
  });

  suite.test('the enrolment tool applies NFC to the password, as the web client does', async () => {
    const normalized = 'operator@example.invalid';
    const fromTool = toBase64Url(await deriveClientValue(PASSWORD_DECOMPOSED, normalized));
    const fromWeb = await deriveCredential(PASSWORD_DECOMPOSED, normalized);
    assertEqual(
      'the tool and the web client derive the same key from a DECOMPOSED password. If they do ' +
        'not, an operator who enrols a password containing any non-ASCII character creates an ' +
        'account that can never log in from the web, and the failure looks like a typo',
      fromTool,
      fromWeb,
    );
  });

  suite.test('the enrolment tool treats the two encodings of one password as one password', async () => {
    const normalized = 'operator@example.invalid';
    const decomposed = toBase64Url(await deriveClientValue(PASSWORD_DECOMPOSED, normalized));
    const composed = toBase64Url(await deriveClientValue(PASSWORD_COMPOSED, normalized));
    assertEqual(
      'the enrolment tool is NFC-stable across the two encodings',
      decomposed,
      composed,
    );
  });

  return suite;
}
